repos:
  - repo: local
    hooks:
    - id: rust-clippy
      name: Rust clippy
      description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
      entry: cargo clippy --all-features --all --
      pass_filenames: false
      types: [file, rust]
      language: system
    - id: rust-format
      name: rust-format
      description: Format files with rustfmt.
      entry: cargo fmt --all --
      pass_filenames: true
      types: [file, rust]
      language: system
