[package]
name = "nix-update-tracker"
version = "0.1.0"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]

[dependencies]
chrono = "0.4.0"
clap = "2.26.0"
fern = "0.4"
fs2 = "0.4.3"
libflate = "0.1.12"
log = "0.3"
md5 = "0.3.6"
reqwest = "0.7.3"
serde = "1.0.16"
serde_derive = "1.0.16"
serde_json = "1.0"
regex = "1.0.0"             # An implementation of regular expressions for Rust. This implementation uses finite automata and gua…
lazy_static = "1.0.0"           # A macro for declaring lazily evaluated statics in Rust.

