[package]
name = "nix-update-tracker"
version = "0.1.0"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]

[dependencies]
clap = "2.26.0"
reqwest = "0.7.3"
serde_json = "1.0"
serde = "1.0.16"
serde_derive = "1.0.16"
log = "0.3"
fern = "0.4"
chrono = "0.4.0"
libflate = "0.1.12"
