[package]
name = "nix-vuln-scanner"
version = "0.1.0"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]

[dependencies]
chrono = "0.4.0"
clap = "2.26.0"
error-chain = "0.12.0"                 # Yet another error boilerplate library.
fern = "0.4"
fs2 = "0.4.3"
git2 = "0.7.2"                           # Bindings to libgit2 for interoperating with git repositories. This library is both thr…
lazy_static = "1.0.0"           # A macro for declaring lazily evaluated statics in Rust.
libflate = "0.1.12"
log = "0.3"
md5 = "0.3.6"
num_cpus = "1.8.0"            # Get the number of CPUs on a machine.
openat = "0.1.15"          #     A wrapper around openat, symlinkat, and similar system calls
rayon = "1.0"
regex = "1.0.0"             # An implementation of regular expressions for Rust. This implementation uses finite automata and gua…
reqwest = "0.7.3"
serde = "1.0.16"
serde_derive = "1.0.16"
serde_json = "1.0"
threadpool = "1.7.1"                    # A thread pool for running a number of jobs on a fixed set of worker threads.
time = "0.1.40"             # Utilities for working with time-related functions in Rust.
