[package]
name = "nix-vuln-scanner"
version = "0.1.2-dev"
authors = ["Andreas Rammhold <andreas@rammhold.de>"]

[dependencies]
actix-web = "0.7"                 # Actix web is a simple, pragmatic and extremely fast web framework for Rust.
chrono = "0.4"
clap = "2.26"
dialog=  { git = "https://git.darmstadt.ccc.de/maralorn/dialog-rs.git" }
diesel = { features = ["sqlite"], version =  "1.3" }                   # A safe, extensible ORM and Query Builder for PostgreSQL, SQLite, and MySQL
error-chain = "0.12"                 # Yet another error boilerplate library.
fern = "0.5"
fs2 = "0.4"
git2 = "0.7"                           # Bindings to libgit2 for interoperating with git repositories. This library is both thr…
itertools = "0.7"         # Extra iterator adaptors, iterator methods, free functions, and macros.
lazy_static = "1.1"           # A macro for declaring lazily evaluated statics in Rust.
libflate = "0.1"
log = "0.4"
md5 = "0.3"
mktemp = "0.3"
num_cpus = "1.8"            # Get the number of CPUs on a machine.
openat = "0.1"          #     A wrapper around openat, symlinkat, and similar system calls
rayon = "1.0"
regex = "1.0"             # An implementation of regular expressions for Rust. This implementation uses finite automata and gua…
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
threadpool = "1.7"                    # A thread pool for running a number of jobs on a fixed set of worker threads.
time = "0.1"             # Utilities for working with time-related functions in Rust.
walkdir = "2.2.5"                  # Recursively walk a directory.

[dependencies.brotli]
version = "2.5"
default-features = false
